Repository v2thegreat/SOEN-341-PRJKT, pull requests merged in 2019-11, with the labels that each got.

#49 Cleaning github
  .travis.yml
Labels: documentation

#50 Complete clean up of github repository
  .idea/.gitignore
  .idea/SOEN-341-PRJKT.iml
  .idea/jsLibraryMappings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Channel.js
  SOEN341_copy.html
  User.js
  channellist/channellist.js
  channelview/channelview.js
  channelview/styles.js
  index.css
  index.js
  serviceWorker.js
  soen341.html
  soen341script.js
  soen341theme.css
  src/channellist/channellist.js
  src/channellist/styles.js
  src/dashboard/dashboard.js
  src/index.css
  src/index.js
  src/login/login.js
  src/login/styles.js
  src/logo.svg
  src/serviceWorker.js
  src/signup/signup.js
  src/signup/styles.js
Labels: documentation

#51 Updated readme
  README.md
Labels: documentation

#52 Revised old features and added new feature.
  channellist/channellist.js
  channellist/styles.js
  channeltextbox/channeltextbox.js
  channeltextbox/styles.js
  channelview/channelview.js
  channelview/scrollbar.js
  channelview/styles.js
  dashboard/dashboard.js
  dashboard/styles.js
  newchannel/newchannel.js
  newchannel/styles.js
Labels: Backend, UI, User Stories, bug, enhancement

#53 Update joining channel feature
  channellist/channellist.js
  channellist/styles.js
  channelview/channelview.js
  dashboard/dashboard.js
  joinchannel/joinchannel.js
  joinchannel/styles.js
  newchannel/newchannel.js
Labels: Backend, User Stories, enhancement

#54 Joining channel function implementation
  joinchannel/joinchannel.js
Labels: Backend, UI, enhancement

#57 Update Readme file
  README.md
Labels: documentation, enhancement

#56 Coding Format
  channellist/channellist.js
  channellist/styles.js
  channeltextbox/channeltextbox.js
  channeltextbox/styles.js
  channelview/channelview.js
  channelview/scrollbar.js
  channelview/styles.js
  dashboard/dashboard.js
  dashboard/styles.js
  joinchannel/joinchannel.js
  joinchannel/styles.js
  login/login.js
  login/styles.js
  newchannel/newchannel.js
  newchannel/styles.js
  signup/signup.js
  signup/styles.js
Labels: Backend, documentation

#59 Added Tests For All Classes
  index.test.js
Labels: Backend
