Repository v2thegreat/SOEN-341-PRJKT, pull requests merged in 2019-10, with the labels that each got.

#26 Front-end files
  soen341.html
  soen341script.js
  soen341theme.css
Labels: UI, bug, help wanted

#27 Add files via upload
  soen341.html
  soen341script.js
  soen341theme.css
Labels: UI, User Stories, dependencies, enhancement

#32 Users
  SOEN341_copy.html
  User.js
Labels: Backend, enhancement

#40 Channel Update
  Channel.js
Labels: Backend, User Stories

#44 Functional UI with login and sign up features.
  channellist/channellist.js
  channellist/styles.js
  dashboard/dashboard.js
  index.css
  index.js
  login/login.js
  login/styles.js
  logo.svg
  serviceWorker.js
  signup/signup.js
  signup/styles.js
Labels: Backend, UI, User Stories, enhancement

#46 Message function update
  channellist/channellist.js
  channeltextbox/channeltextbox.js
  channeltextbox/styles.js
  channelview/channelview.js
  channelview/styles.js
  dashboard/dashboard.js
  dashboard/styles.js
Labels: Backend, bug
